### ISSUE TITLE
Custom field from netbox

### ISSUE THREAD

**Issue by raivisj** [TheNetworkGuy/netbox-zabbix-sync#20]
Hello, is there a possibility to use custom field from netbox with -l flag to create hostgroup in zabbix, like site/custom field/dev_role ?

**Comment by TheNetworkGuy** [comment]
Currently this is not supported. It does oppose to a nice challenge :)

Could you elaborate your use case?

**Comment by TheNetworkGuy** [comment]
I think that this has been implemented on a new branch, feel free to try it out!

**Comment by TheNetworkGuy** [comment]
Updated documentation, closing this issue.
