### ISSUE TITLE
AttributeError: object has no attribute "name"

### ISSUE THREAD

**Issue by rasulovk** [TheNetworkGuy/netbox-zabbix-sync#22]
Version of netbox :
1b92ee3a14d6 (v3.3.2)

Python 3 version:
Python 3.9.2

Zabbix version:
Zabbix 5.4.8

After adding Primary IP in netbox following error occurs:

Traceback (most recent call last):
  File "/home/devlin/Docker/netbox/netbox-zabbix-sync/netbox_zabbix_sync.py", line 740, in <module>
    main(args)
  File "/home/devlin/Docker/netbox/netbox-zabbix-sync/netbox_zabbix_sync.py", line 83, in main
    device = NetworkDevice(nb_device, zabbix, netbox_journals,
  File "/home/devlin/Docker/netbox/netbox-zabbix-sync/netbox_zabbix_sync.py", line 191, in __init__
    self._setBasics()
  File "/home/devlin/Docker/netbox/netbox-zabbix-sync/netbox_zabbix_sync.py", line 212, in _setBasics
    f"found for {self.nb.device_type.name}.")
  File "/home/devlin/.local/lib/python3.9/site-packages/pynetbox/core/response.py", line 298, in __getattr__
    raise AttributeError('object has no attribute "{}"'.format(k))
AttributeError: object has no attribute "name"

**Comment by rasulovk** [comment]
@TheNetworkGuy Hi, any updates ?

**Comment by TheNetworkGuy** [comment]
Good day, i have checked out the code today but unfortunately i am unable to replicate the issue. The only explanation that i can give is that you are trying to sync a Netbox device which you haven't given a name. I haven't made a check for this specific scenario. Can you confirm that all the devices which you are trying to sync also have a name in Netbox?

**Comment by rasulovk** [comment]
@TheNetworkGuy Sorry for late reply. Configuration screnshoot has been attached. 
<img width="1180" alt="Screen Shot 2022-11-24 at 22 05 15" src="https://user-images.githubusercontent.com/17510490/203845532-e9c7325a-e351-4e60-8668-c4d8ade30cd3.png">

**Comment by rasulovk** [comment]
@TheNetworkGuy If I remove IP address from "Primary IPv4", then script will work.

**Comment by TheNetworkGuy** [comment]
This behaviour is expected since the script will skip any devices which do not have a valid primary IPv4 address.

Can you share on how you are running the script and with what parameters? Thank you for sharing the device details, i'll try to replicate the setup.

**Comment by TheNetworkGuy** [comment]
By the way i just took a better look at your setup and it seems that you haven't created any custom fields for the Zabbix ID. Is this assumption correct? https://github.com/TheNetworkGuy/netbox-zabbix-sync#netbox-settings

**Comment by TheNetworkGuy** [comment]
Yes i can replicate the issue now. It seems that when the NB custom field for Zabbix templates is not configured the script tries to warn you for this by mentioning the device type name. However this value has been modified by Netbox to the display variable. I'll push the code later today, meanwhile your problem will be fixed by adding the 2 custom fields like i mentioned previously :)

**Comment by rasulovk** [comment]
@TheNetworkGuy Oh yes, I don't understand how to configure it. I did only SNMP part 
<img width="906" alt="Screen Shot 2022-11-25 at 18 56 11" src="https://user-images.githubusercontent.com/17510490/204010881-26f690c0-36ef-4281-b2da-1aa336db9177.png">

Could you please show me what I did wrong, I don't want see this error: )
" 2022-11-24 19:46:15,327 - Netbox-Zabbix-sync - WARNING - Custom field zabbix_hostid not found for device123."

Thanks in advance

**Comment by TheNetworkGuy** [comment]
The config context data is not required if you are using the default Zabbix parameters. If you don't specify the config context then the following default interface config will be applied:

 - Bulk requests will be enabled
 - SNMP version 2
 - UDP 161
 - SNMP community {$SNMP_COMMUNITY}

The Zabbix macro {$SNMP_COMMUNITY} will by default resolve to "public". You can verify this under the Zabbix menu Administration -> General -> Macros.

So to summarize, the default script implementation will do exactly what you have in your config context data. It won't hurt or anything but right now it does not provide anything extra either :)

As for your other question, create 2 custom fields as mentioned here: https://github.com/TheNetworkGuy/netbox-zabbix-sync#custom-fields. Steps on how to create custom fields can be found here: https://docs.netbox.dev/en/stable/customization/custom-fields/. If you do these steps then the error will go away.

To help you understand why you need these 2 fields:
 - The zabbix_hostid custom field is required for linking a Zabbix host to the Netbox device object.
 - The zabbix_templateid custom field is required for specifying a Zabbix template to a device type. For instance in your case all Fortinet FS-224E devices will get the same Zabbix template.

**Comment by rasulovk** [comment]
@TheNetworkGuy I feel I'm close to proper configuration, just last question:
Am I right now? :
<img width="1173" alt="Screen Shot 2022-11-25 at 23 16 55" src="https://user-images.githubusercontent.com/17510490/204044287-f06ec6cf-8a5c-45f2-a37c-7b42d009359c.png">

<img width="1173" alt="Screen Shot 2022-11-25 at 23 17 21" src="https://user-images.githubusercontent.com/17510490/204044299-23f97cd8-b19b-4479-93c4-b97ac9daf437.png">

<img width="1173" alt="Screen Shot 2022-11-25 at 23 17 54" src="https://user-images.githubusercontent.com/17510490/204044308-177edcdd-3dd4-4279-9cf8-f3281fb2167b.png">

Looks like I missed something :)

**Comment by TheNetworkGuy** [comment]
This looks great, custom fields are OK.

The script tells you that the hostgroup "ATS building/Fortinet/Access switch" does not exist in Zabbix. You can fix this in 2 ways:
 - Create the hostgroup manually
 - Use the -H flag to let the script create the hostgroup for you.

If you are using a Zabbix account with permissions to create hostgroups, i would recommend going for the -H flag. https://github.com/TheNetworkGuy/netbox-zabbix-sync#flags

**Comment by rasulovk** [comment]
@TheNetworkGuy Thanks a lot. I would to new feature, I'm using "oxidized" solution for backup network equipment, Can we add new script to add network name and ip to "oxidized" text configuration? 

https://github.com/ytti/oxidized

**Comment by TheNetworkGuy** [comment]
@rasulovk Glad that you got it working.

As for Oxidized, we use this as well with Netbox. However instead of using a script to add data to a text file, use the HTTP source. I cannot explain everything since this goes way out of the scope of Netbox - Zabbxi sync. But please check this post, it uses the Netbox API to provision the Oxidized inventory. https://www.reddit.com/r/networking/comments/o78vvp/comment/h3b934o/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by rasulovk** [comment]
@TheNetworkGuy thanks a lot, you help me a lot.
