### ISSUE TITLE
Environment variable ZABBIX_HOST has not been defined.

### ISSUE THREAD

**Issue by patricklind** [TheNetworkGuy/netbox-zabbix-sync#26]
ython3 netbox_zabbix_sync2.py
2023-02-06 13:07:20,958 - Netbox-Zabbix-sync - ERROR - Environment variable ZABBIX_HOST has not been defined.
Traceback (most recent call last):
  File "/opt/apps/netbox-zabbix-sync/netbox_zabbix_sync2.py", line 716, in <module>
    main(args)
  File "/opt/apps/netbox-zabbix-sync/netbox_zabbix_sync2.py", line 47, in main
    raise EnvironmentVarError(e)
__main__.EnvironmentVarError: Environment variable ZABBIX_HOST has not been defined

**Comment by patricklind** [comment]
Environment variable is filled

**Comment by TheNetworkGuy** [comment]
Is the ENV variable declared under the same user that is running the script?

Could you run the "env | grep ZABBIX" comman, after that run the script under the same user again and paste the output in this issue? You can anonymize the output should it contain sensitive information. I can also see that you renamed the file to *sync2.py. Did you make any changes to the code that contains the environment variable logic? If so than i cannot do much troubleshooting here :P

**Comment by patricklind** [comment]
root@zabbix:/opt/apps/netbox-zabbix-sync# python3 netbox_zabbix_sync.py | env | grep ZABBIX
2023-02-06 15:24:15,816 - Netbox-Zabbix-sync - ERROR - Environment variable ZABBIX_HOST has not been defined.
Traceback (most recent call last):
  File "/opt/apps/netbox-zabbix-sync/netbox_zabbix_sync.py", line 760, in <module>
    main(args)
  File "/opt/apps/netbox-zabbix-sync/netbox_zabbix_sync.py", line 44, in main
    raise EnvironmentVarError(e)
__main__.EnvironmentVarError: Environment variable ZABBIX_HOST has not been defined.
root@zabbix:/opt/apps/netbox-zabbix-sync#  env | grep ZABBIX
root@zabbix:/opt/apps/netbox-zabbix-sync# 
root@zabbix:/opt/apps/netbox-zabbix-sync# 
root@zabbix:/opt/apps/netbox-zabbix-sync# 
root@zabbix:/opt/apps/netbox-zabbix-sync# cat config.py | grep ZABBIX
ZABBIX_HOST="https://zabbix.vigfestival.network"

**Comment by TheNetworkGuy** [comment]
Ah i see you declared the value in the config.py file. This is (for now) not the correct location for this type of data since storing passwords in plain text / in config files is not recommended.

Please set the environment variable like so:

```
[root@docker ~]# export ZABBIX_HOST="https://zabbix.home.local"
[root@docker ~]# env | grep ZABBIX
ZABBIX_HOST=https://zabbix.home.local
[root@docker ~]#
```

Please do this for all the required variables:

ZABBIX_HOST="https://zabbix.local"
ZABBIX_USER="username"
ZABBIX_PASS="Password"
NETBOX_HOST="https://netbox.local"
NETBOX_TOKEN="secrettoken"

**Comment by patricklind** [comment]
can i get it into a .env  file ?

**Comment by TheNetworkGuy** [comment]
How you import the environment variables is up to you and more of a linux specific question. If you want to set the Zabbix host, password and token information in clear text in a text file than you could do this and modify the code to import said variables. However i won't support this and won't advice you to do so.

Instead, look at the different ways of setting environment variables under users or how to set them for a systemctl service.

**Comment by TheNetworkGuy** [comment]
Closing this one due to inactivity.
