### ISSUE TITLE
Using custom device fields with other types (e.g. Boolean)

### ISSUE THREAD

**Issue by mwllgr** [TheNetworkGuy/netbox-zabbix-sync#28]
Hello,

this project currently does not allow the usage of custom field types other than `text`:

```python
device_cfs = netbox.extras.custom_fields.filter(type="text", content_type_id=23)
```

Why exactly are you filtering for only text-type fields? Are there any disadvantages in removing the type filter?
```python
device_cfs = netbox.extras.custom_fields.filter(content_type_id=23)
```

**Comment by mwllgr** [comment]
Thanks for your quick reply - we have some Boolean custom fields which we'd have to include too. Let's call the field "monitor" and we'd only want to include all the items that have the monitor field set to true.

**Comment by TheNetworkGuy** [comment]
I think that we are talking about 2 different things. The custom field construction that you mention is only used for the hostgroup name generation.

Corrent me if i'm wrong but you want to filter your devices with a custom field 0 / 1 value. You can easily do this as follows in the config file:

nb_device_filter = {"cf_monitor": True}

Is this correct?

**Comment by mwllgr** [comment]
It was a configuration issue on our side. Everything works as expected - but thanks for the heads-up!
