### ISSUE TITLE
add snmp version

### ISSUE THREAD

**Issue by patricklind** [TheNetworkGuy/netbox-zabbix-sync#32]
Is it possible to add a select box to snmp v1 / v2c

**Comment by TheNetworkGuy** [comment]
Ah i see i made the script expecting SNMPv2 and SNMPv1 but never calculated for SNMPv1. I'll adjust the script to take SNMPv1 as well. However at the same time i would also like to advice to check if the equipment is SNMPv2 or v3 capable :P

**Comment by TheNetworkGuy** [comment]
`if(self.interface["details"]["version"] == '2'):` should be either 1 or 2. Easy fix.
