### ISSUE TITLE
templates_config_context not defined

### ISSUE THREAD

**Issue by Domisiding** [TheNetworkGuy/netbox-zabbix-sync#34]
Hey,
in the latest version "templates_config_context" (218) is not defined and there comes an error.

**Comment by TheNetworkGuy** [comment]
I might have pushed some code yesterday that was contaminated with code that was meant for a different branch. Will look at it ASAP.

**Comment by TheNetworkGuy** [comment]
Can you do a pull again on the main repo and check if the script works again?

**Comment by Domisiding** [comment]
Yes it works

This afternoon I already removed it manually for our production. Didn't want to create a pull request because I thought it was something for the future
