### ISSUE TITLE
add Config Template

### ISSUE THREAD

**Issue by patricklind** [TheNetworkGuy/netbox-zabbix-sync#39]
hi,

can you add if "Local Config Context Data" in use then use "Config Template"

**Comment by TheNetworkGuy** [comment]
This could be implemented quite easily! I'll take a look at it this week :)

**Comment by TheNetworkGuy** [comment]
"This week" is somewhat loosely in my world. Working on this right now.

**Comment by TheNetworkGuy** [comment]
Just pushed this functionallity to the project and mentioned the functionallity over here: https://github.com/TheNetworkGuy/netbox-zabbix-sync?tab=readme-ov-file#template-source. Take a look at the new templates_config_context_overrule variable :)
