### ISSUE TITLE
Request sync  Latitude and Longitude to Zabbix

### ISSUE THREAD

**Issue by patricklind** [TheNetworkGuy/netbox-zabbix-sync#44]
Hi,

Can you add Latitude and Longitude from netbox  to Zabbix Inventory Location latitude and Location longitude ?

**Comment by q1x** [comment]
Might be interesting to include more mappings of Netbox fields to inventory fields like serial number, manufacturer, device type, etc.

**Comment by patricklind** [comment]
> Might be interesting to include more mappings of Netbox fields to inventory fields like serial number, manufacturer, device type, etc.

yes please

**Comment by TheNetworkGuy** [comment]
So this would be some kind of mapper configured in the config.py file. I'll see if i can work on this issue later today.

**Comment by TheNetworkGuy** [comment]
Well that went wrong, i handled enhancement #47 first. I'll soon start working on some kind of general mapping functionallity.

**Comment by q1x** [comment]
This should be fixed with the merge of #55 , can you test if this works for you?

**Comment by TheNetworkGuy** [comment]
Closing this one due to inactivity. Feature has been implemented.
