### ISSUE TITLE
Add dockerfile for Docker deployments

### ISSUE THREAD

**Issue by TheNetworkGuy** [TheNetworkGuy/netbox-zabbix-sync#46]
Title says it all. Minimal Python setup that will run the script.

**Comment by q1x** [comment]
Working on this, including github workflow to automatically push the image to GHCR.io.
See #55 and further work in https://github.com/q1x/netbox-zabbix-sync/tree/dockertest

**Comment by q1x** [comment]
I think we can close this one?

**Comment by TheNetworkGuy** [comment]
Closed!
