### ISSUE TITLE
More hostgroup variables

### ISSUE THREAD

**Issue by TheNetworkGuy** [TheNetworkGuy/netbox-zabbix-sync#47]
Netbox has more fields which could be useful with the generation of hostgroups. Adding these variables would allow users to have a finer degree of customization in their environments.

I would also propose to move this functionallity to the config file instead of calling it as a variable when running the script.

The following variables have been tested and can be implemented:

- Site region name
- Site group name
- Device location name
- Tenant group name

These variables come on top of the existing variables:

- Tenant name
- Site name
- Manufacturer name
- Device role

**Comment by TheNetworkGuy** [comment]
Started work on this in new branch. New variable functionallity is done. Next step is moving functionallity from the -l flag to the config.py file.

**Comment by TheNetworkGuy** [comment]
This issue is done in the dev branch. However i want to perform all of the work listed in #48 and mark all hte changes in the first 1.0 release since upgrading to this release requires less arguments and more use of the config.py file.

**Comment by TheNetworkGuy** [comment]
Implemented.

**Comment by q1x** [comment]
When using nested 'site groups', only the lowest member of the tree is used in the sync, would be cool if we could add the full 'site groups' hierarchy as nested Zabbix host groups. 

Also, I have a need to use 'Facility' in the group tree.
