### ISSUE TITLE
netbox v4.0.6 

### ISSUE THREAD

**Issue by patricklind** [TheNetworkGuy/netbox-zabbix-sync#67]
Can you make a quick fix ?

Traceback (most recent call last):
  File "/opt/apps/netbox-zabbix-sync/netbox_zabbix_sync.py", line 200, in <module>
    main(args)
  File "/opt/apps/netbox-zabbix-sync/netbox_zabbix_sync.py", line 127, in main
    nb_version = netbox.version
                 ^^^^^^^^^^^^^^
  File "/opt/apps/netbox-zabbix-sync/.venv/lib/python3.11/site-packages/pynetbox/core/api.py", line 113, in version
    ).get_version()
      ^^^^^^^^^^^^^
  File "/opt/apps/netbox-zabbix-sync/.venv/lib/python3.11/site-packages/pynetbox/core/query.py", line 198, in get_version
    raise RequestError(req)
pynetbox.core.query.RequestError: The request failed with code 403 Forbidden: {'detail': 'Authentication credentials were not provided.'}

**Comment by patricklind** [comment]
https://github.com/netbox-community/pynetbox/issues/612

**Comment by TheNetworkGuy** [comment]
Hmm i'll take a look at this. Seems like i missed some stuff in the pynetbox dependancy

**Comment by patricklind** [comment]
> Hmm i'll take a look at this. Seems like i missed some stuff in the pynetbox dependancy

it is.

my quick fix is: LOGIN_REQUIRED=false

**Comment by TheNetworkGuy** [comment]
So i did some digging and i have the following 2 points:

First off i think that an underlying issue of this script (in this case a bug in hte pynetbox library) should be handled by the pynetbox team. It does not make sense to implement bug fixes all over the place while a simple fix upstream would fix the issue for all dependend projects.

Secondly i am wondering for your case specifically what your python versions, pynetbox version. netbox version and script version is? I just ran this sample script and don't get an error back. Running on Windows:
```
Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pynetbox import api
>>> from os import environ
>>>
>>> netbox_host = environ.get("NETBOX_HOST")
>>> netbox_token = environ.get("NETBOX_TOKEN")
>>> netbox = api(netbox_host, token=netbox_token, threading=True)
>>>
>>> nb_version = netbox.version
>>> print(nb_version)
4.0
>>>
```
Dependencies:
Python 3.12.4
pynetbox 7.3.3
Netbox 4.0.6
Latest release of the sync script (git pull)

**Comment by ivlru** [comment]
Hi, patricklind

> my quick fix is: LOGIN_REQUIRED=false

I placed this into "netbox-zabbix-sync/config.py"  but it still alarms:

pynetbox.core.query.RequestError: The request failed with code 403 Forbidden: {'detail': 'Authentication credentials were not provided.'}

Could you please repeat how to fix that? Thank you!

**Comment by patricklind** [comment]
> LOGIN_REQUIRED
https://demo.netbox.dev/static/docs/configuration/optional-settings/#login_required
my quick fix is: LOGIN_REQUIRED=false

**Comment by ivlru** [comment]
Thank you!
