### ISSUE TITLE
Change name in Zabbix to a description from Netbox

### ISSUE THREAD

**Issue by Winstonshead** [TheNetworkGuy/netbox-zabbix-sync#77]
Greetings!
I want to use some characters in device names in Netbox that cannot be used in host names in Zabbix, so I get an error, eventually the host is not added from Netbox.
I would like Zabbix to take the device description from Netbox and substitute it into the hostname field. How can I do this?
Thanks!

**Comment by TheNetworkGuy** [comment]
Hi! Can you give an example and some logging? The scenario that you are describing should be fixed with #58 .

**Comment by Winstonshead** [comment]
> Hi! Can you give an example and some logging? The scenario that you are describing should be fixed with #58 .

I use Cyrillic on Netbox
![IMG_20241024_162959_341](https://github.com/user-attachments/assets/9e91bc4d-df67-40dd-ac8e-f5092ce98fa7)

**Comment by TheNetworkGuy** [comment]
Thanks! I'm guessing that the character that's causing this headache is the space. I'll check if i can add this to the list of exceptions, should be a pretty easy fix :)

**Comment by TheNetworkGuy** [comment]
@Winstonshead If you have the time to copy / paste that warning message then that would help me out a lot! Thanks in advance.

**Comment by TheNetworkGuy** [comment]
I'll close this issue for now since its getting stale. You can always re-open this issue if you have more information.

**Comment by TheNetworkGuy** [comment]
@Winstonshead No worries, that stuff tends to happen :) Thanks for your reply, i'll push it to the development branch on which i am currently working on!

**Comment by Winstonshead** [comment]
Oh, cool! I will test later, thank you very much
