### ISSUE TITLE
Name resolve error

### ISSUE THREAD

**Issue by aseok** [TheNetworkGuy/netbox-zabbix-sync#78]
Hi. getting following error running the docker container on ubuntu22:
requests.exceptions.ConnectionError: HTTPConnectionPool(host='netbox-docker-netbox-1', port=8080): Max retries exceeded with url: /api/extras/custom-fields/?type=text&content_type_id=23&limit=0 (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fa729ce9f10>: Failed to resolve 'netbox-docker-netbox-1' ([Errno -2] Name does not resolve)"))

zabbix-server and netbox already running and functional on their separate containers with 10051:10051 and 8080 internal ports respectively on same ubuntu22.

**Comment by TheNetworkGuy** [comment]
Please double check your URL and  Netbox token. And i'll do some adjustments in the code to help with better logging instead of this ugly crash.

**Comment by TheNetworkGuy** [comment]
I've added some checks in the new development branch to give you better logging:

`2024-11-06 15:56:14,709 - Netbox-Zabbix-sync - ERROR - Unable to connect to Netbox with URL http://localhoost:8000. Please check the URL and status of Netbox.

`2024-11-06 15:55:58,931 - Netbox-Zabbix-sync - ERROR - Netbox error: The request failed with code 403 Forbidden: {'detail': 'Invalid token'}

**Comment by TheNetworkGuy** [comment]
I'll close this for now due to it being stale.

**Comment by aseok** [comment]
zabbix and netbox containers are connected over zabbix_zabbixnet docker network(docker exec -it zabbix-server ping netbox-docker-netbox-1 works). here's netbox container curl output:
curl -i http://localhost:82
HTTP/1.1 302 Found
Content-Type: text/html; charset=utf-8
Location: /login/?next=/
X-Request-ID: 5b85427b-f3ee-46fb-8b22-542c8c4aaeea
Vary: HX-Request, Accept-Language, Cookie, origin
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin
Cross-Origin-Opener-Policy: same-origin
X-Frame-Options: SAMEORIGIN
