### ISSUE TITLE
From zabbix to netbox

### ISSUE THREAD

**Issue by KIvanov-1984** [TheNetworkGuy/netbox-zabbix-sync#84]
Hello, is there a reverse script for uploading devices from zabbix to netbox?

**Comment by q1x** [comment]
Hi @KIvanov-1984, we don't currently offer this workflow and I would argue that this is actually against best practices with regard to the [Single-Source-of-Truth](https://en.wikipedia.org/wiki/Single_source_of_truth) paradigm.

That being said, I can understand that moving towards a SSOT requires some initial gathering of existing inventory and Zabbix could be a valid source in this phase. I looked around a bit for another project that might offer this but I can not find a quick solution for you.

Sorry, good luck on your endeavor and let us know if you find a solution!
