### ISSUE TITLE
[BUG] site_group and region traversal seems to be broken

### ISSUE THREAD

**Issue by q1x** [TheNetworkGuy/netbox-zabbix-sync#87]
I've been testing with `site_group` and `region` traversal when using those items in hostgroup names, but it seems like the logic has been broken after switching to the new setup with modules.

I think it fails around this point in the code:

https://github.com/TheNetworkGuy/netbox-zabbix-sync/blob/867749ddd69814b244c807bbb5b0b5abef2d00ea/modules/device.py#L105
https://github.com/TheNetworkGuy/netbox-zabbix-sync/blob/867749ddd69814b244c807bbb5b0b5abef2d00ea/modules/hostgroups.py#L72

We need to investigate this further.

**Comment by TheNetworkGuy** [comment]
Reproducable. Long story short:

Under class Hostgroup() the function _set_format_options() calls function generate_parents(). This function is called when initializing a child.

The function generate_parents() is depending on the dictionary self.nested_objects. This dictionary is empty until the function set_nesting() is called.

So the whole problem is that _set_format_options() is called before set_nesting(). There are a couple of tricks to fix this. Including making a better flow in the code or defining a dedicated function for calculating the region and site_group variables. However you can also do it dirty and call the same function twice. Once again not a big fan of this setup but it.... works.

```
    def set_nesting(self, nested_sitegroup_flag, nested_region_flag,
                    nb_groups, nb_regions):
        """Set nesting options for this Hostgroup"""
        self.nested_objects = {"site_group": {"flag": nested_sitegroup_flag, "data": nb_groups},
                               "region": {"flag": nested_region_flag, "data": nb_regions}}
        # Recheck all the formatting options
        self._set_format_options()
```
Notice that i've added the following code to force a recalculation of all the format_options:
```
# Recheck all the formatting options
        self._set_format_options()
```

**Comment by TheNetworkGuy** [comment]
I would suggest editing the code and fixing it the dirty way. We can leave this issue open for now but the functionallity will work again and that gives us time to make a more elegant solution.

**Comment by q1x** [comment]
Ok, I had a look and I might have found a decent solution.
Let me test a little more and cook up a pull request :)
